package examples
package main






































































































































*/}	s.PrintReport()	}		return		log.Printf("[!] Scan failed: %v\n", err)	if err := s.Run(); err != nil {	// s.SetAIProvider(aiProvider)	// [AI setup code would go here - see main.go for full example]	s.SetInsecureTLS(true)	s.SetTLS(true)	s := scanner.NewScanner(target, port)	// Create scanner	port := 443	target := "example.com"func exampleWithAI() {/*// Uncomment and use when AI provider is configured// ExampleWithAI demonstrates integration with AI analysis}	fmt.Println("\n[*] Full scan completed. Results above.")	// Print detailed report	}		return		log.Printf("[!] Scan failed: %v\n", err)	if err := s.Run(); err != nil {	// Run full scan (includes all techniques)	fmt.Printf("[*] TLS: Enabled (insecure mode)\n\n")	fmt.Printf("[*] Confidence threshold: 50%%\n")	fmt.Printf("[*] Scanning %s:%d\n", target, port)	s.SetConfidenceThreshold(0.50) // 50% confidence threshold	s.SetInsecureTLS(true)	s.SetTLS(true)	s := scanner.NewScanner(target, port)	// Create scanner with custom threshold	port := 443	target := "lab.web-security-academy.net"func advancedScan() {// advancedScan demonstrates advanced configuration options}	}		fmt.Printf("  - Obfuscation '%s': %d bytes\n", obf, len(payload))		payload, _ := gen.GenerateObfuscatedTEPayload(smoggledBody, obf)	for _, obf := range obfuscations {	fmt.Println("\nOther obfuscation patterns:")	obfuscations := []string{"x-chunked", "chunked;q=0.5", "deflate"}	// Generate with other obfuscation values	fmt.Printf("Payload (formatted):\n%s\n", payload)	fmt.Printf("Payload (raw bytes):\n%q\n\n", payload)	}		return		log.Printf("[!] Payload generation failed: %v\n", err)	if err != nil {	payload, err := gen.GenerateObfuscatedTEPayload(smoggledBody, "cow")	fmt.Println("Generating Obfuscated-TE payload with 'cow' variant:")	// Generate payload with "cow" obfuscation		"Content-Length: 15\r\n\r\nx=1"		"Content-Type: application/x-www-form-urlencoded\r\n" +	smoggledBody := "POST / HTTP/1.1\r\nHost: " + target + "\r\n" +	// Define the smuggled request	gen.AddHeader("Connection", "close")	gen.SetPath("/")	gen := payload.NewGenerator(target, port)	port := 443	target := "example.com"func payloadGeneration() {// payloadGeneration demonstrates how to generate obfuscated TE payloads}	s.PrintReport()	// Print results	}		return		log.Printf("[!] Test failed: %v\n", err)	if err := s.TestObfuscatedTE(); err != nil {	fmt.Println("[*] Testing for Obfuscated-TE vulnerability...")	// Test just obfuscated TE	}		return		log.Printf("[!] Baseline capture failed: %v\n", err)	if err := s.CaptureBaseline(); err != nil {	fmt.Printf("[*] Capturing baseline for %s:%d\n", target, port)	// Capture baseline	s.SetInsecureTLS(true)	s.SetTLS(true)	s := scanner.NewScanner(target, port)	// Create scanner	port := 443	target := "example.com"func basicScan() {// basicScan demonstrates the simplest way to test for obfuscated TE}	advancedScan()	fmt.Println("\n\n=== Example 3: Advanced Configuration ===\n")	// Example 3: Advanced detection with custom options	payloadGeneration()	fmt.Println("\n\n=== Example 2: Custom Payload Generation ===\n")	// Example 2: Payload generation	basicScan()	fmt.Println("=== Example 1: Basic Obfuscated-TE Detection ===\n")	// Example 1: Basic CLI-style scanningfunc main() {// ExampleObfuscatedTEDetection demonstrates how to use the obfuscated TE detection feature)	"smuggler/internal/scanner"	"smuggler/internal/payload"	"log"	"fmt"import (